import Head from "next/head";

import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import MediaList from "../components/MediaList/MediaList";

export default function Home() {
  const [media, setMedia] = useState({});
  useEffect(() => {
    const fetchData = async () => {
      try {
        // We're fetching from S3 every single request.
        // TODO: https://react-query.tanstack.com/overview
        fetch("api/s3")
          .then((res) => res.json())
          .then((res) => {
            setMedia(res.Contents);
          });
      } catch (err) {
        throw err;
      }
    };
    fetchData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to my video app</h1>
        <MediaList items={media} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://schuster-b.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Schuster
        </a>
      </footer>
    </div>
  );
}
