import Head from "next/head";
import styles from "../styles/Home.module.css";

import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    const fetchData = async () => {
      try {
        fetch("api/s3")
          .then((res) => res.json())
          .then((data) => {
            console.log(data);
          });
      } catch (err) {
        console.error(err);
      }
    };
    fetchData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to my video app</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://schuster-b.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by Schuster
        </a>
      </footer>
    </div>
  );
}
